spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    hikari:
      read-only: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 4000
