spring.application.name=dev-command-hub
spring.datasource.url=jdbc:db2://localhost:50000/APISRHDB
spring.datasource.username=db2inst1
spring.datasource.password=1234qwer1q2w3e4r
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.datasource.hikari.read-only=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
server.port=4000
