spring.application.name=dev-command-hub
spring.datasource.url=${DB_URL:jdbc:db2://localhost:50000/APISRHDB}
spring.datasource.username=${DB_USER:db2inst1}
spring.datasource.password=${DB_PASSWORD:changeme}
spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
spring.datasource.hikari.read-only=false
spring.datasource.hikari.initialization-fail-timeout=0
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.DB2Dialect
server.port=${SERVER_PORT:4000}
